# Generated by Django 3.2.7 on 2021-10-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrabaho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
