# Generated by Django 3.2.7 on 2021-09-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrabaho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymodel',
            options={'verbose_name': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='applicantmodel',
            options={'verbose_name': 'Applicant'},
        ),
        migrations.AlterModelOptions(
            name='experiencedetailmodel',
            options={'verbose_name': 'Experience Detail'},
        ),
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={'verbose_name': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='recruitermodel',
            options={'verbose_name': 'Recruiter'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User'},
        ),
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('H', 'Hiring'), ('A', 'Active'), ('D', 'Done')], max_length=1)),
                ('description', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=50)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrabaho.recruitermodel')),
            ],
            options={
                'verbose_name': 'Job Model',
            },
        ),
        migrations.CreateModel(
            name='ApplicantsListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrabaho.applicantmodel')),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrabaho.jobpostmodel')),
            ],
            options={
                'verbose_name': 'ApplicantsList',
            },
        ),
    ]
