# Generated by Django 3.2.7 on 2021-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="userType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Recruiter"),
                    ("A", "Applicant"),
                    ("L", "LGU Representative"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
