# Generated by Django 3.2.7 on 2021-10-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmodel",
            name="categoryId",
        ),
        migrations.DeleteModel(
            name="CategoryModel",
        ),
    ]
