# Generated by Django 3.2.7 on 2021-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0002_usermodel_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostmodel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("H", "Hiring"), ("A", "Active"), ("D", "Done")],
                max_length=1,
                null=True,
            ),
        ),
    ]
