# Generated by Django 3.2.7 on 2021-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0002_auto_20211018_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantmodel",
            name="skills",
            field=models.ManyToManyField(to="itrabaho.SkillModel"),
        ),
        migrations.AddField(
            model_name="jobpostmodel",
            name="skills",
            field=models.ManyToManyField(to="itrabaho.SkillModel"),
        ),
    ]
