# Generated by Django 3.2.7 on 2021-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrabaho', '0002_auto_20210915_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymodel',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lastLogin',
            field=models.DateField(auto_now=True),
        ),
    ]
