# Generated by Django 3.2.7 on 2021-10-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0003_alter_jobpostmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostmodel",
            name="recruit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="itrabaho.applicantmodel",
            ),
        ),
    ]
