# Generated by Django 3.2.7 on 2021-10-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0002_alter_jobpostmodel_description"),
        ("itrabaho", "0003_auto_20211018_1525"),
    ]

    operations = []
