# Generated by Django 3.2.7 on 2021-10-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0003_alter_jobpostmodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitymodel",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="activitymodel",
            name="label",
        ),
        migrations.RemoveField(
            model_name="activitymodel",
            name="recruiter",
        ),
        migrations.AddField(
            model_name="activitymodel",
            name="userId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="jobPostId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="itrabaho.jobpostmodel",
            ),
        ),
        migrations.CreateModel(
            name="MatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("percentage", models.PositiveSmallIntegerField()),
                (
                    "applicantId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itrabaho.applicantmodel",
                    ),
                ),
                (
                    "jobPostId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itrabaho.jobpostmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
            },
        ),
    ]
