# Generated by Django 3.2.7 on 2022-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0004_merge_20211018_1538"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillmodel",
            options={"verbose_name": "Skill"},
        ),
        migrations.AlterField(
            model_name="matchmodel",
            name="rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
