# Generated by Django 3.2.7 on 2021-10-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0005_auto_20211011_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitymodel",
            name="userId",
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="applicantReviewId",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="itrabaho.reviewmodel",
            ),
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="recruiterReviewId",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_job_post",
                to="itrabaho.reviewmodel",
            ),
        ),
    ]
