# Generated by Django 3.2.7 on 2021-10-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0005_auto_20211011_1418"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicantslistmodel",
            options={
                "default_related_name": "job_applications",
                "verbose_name": "ApplicantsList",
            },
        ),
        migrations.AlterField(
            model_name="applicantslistmodel",
            name="applicantId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="itrabaho.applicantmodel",
            ),
        ),
        migrations.AlterField(
            model_name="applicantslistmodel",
            name="jobPostId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="itrabaho.jobpostmodel",
            ),
        ),
    ]
