# Generated by Django 3.2.7 on 2021-10-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0005_auto_20211011_1418"),
        ("itrabaho", "0006_auto_20211011_1835"),
    ]

    operations = []
