# Generated by Django 3.2.7 on 2021-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0007_merge_0005_auto_20211011_1418_0006_auto_20211011_1835"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpostmodel",
            name="recruitId",
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("H", "Hiring"), ("A", "Active"), ("D", "Done")],
                default="H",
                max_length=1,
                null=True,
            ),
        ),
    ]
