# Generated by Django 3.2.7 on 2021-10-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0006_auto_20211014_2338"),
        ("itrabaho", "0007_merge_0005_auto_20211011_1418_0006_auto_20211011_1835"),
    ]

    operations = []
