# Generated by Django 3.2.7 on 2021-10-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrabaho", "0008_merge_20211015_0236"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpostmodel",
            name="recruitId",
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("H", "Hiring"), ("A", "Active"), ("D", "Done")],
                default="H",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
