# Generated by Django 3.2.7 on 2021-10-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrabaho', '0011_alter_applicantmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='datetimeEnded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='applicantId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_jobs', to='itrabaho.applicantmodel'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='recruiterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='itrabaho.recruitermodel'),
        ),
    ]
