# Generated by Django 3.2.11 on 2022-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrabaho', '0012_auto_20211017_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
